:terms:
    - :id: AL
      :term: Alabama
    - :id: AK
      :term: Alaska
    - :id: AZ
      :term: Arizona
    - :id: AR
      :term: Arkansas
    - :id: CA
      :term: California
    - :id: CO
      :term: Colorado
    - :id: CT
      :term: Connecticut
    - :id: DE
      :term: Delaware
    - :id: FL
      :term: Florida
    - :id: GA
      :term: Georgia
    - :id: HI
      :term: Hawaii
    - :id: ID
      :term: Idaho
    - :id: IL
      :term: Illinois
    - :id: IN
      :term: Indiana
    - :id: IA
      :term: Iowa
    - :id: KS
      :term: Kansas
    - :id: KY
      :term: Kentucky
    - :id: LA
      :term: Louisana
    - :id: ME
      :term: Maine
    - :id: MD
      :term: Maryland
    - :id: MA
      :term: Massachusetts
    - :id: MI
      :term: Michigan
    - :id: MN
      :term: Minnesota
    - :id: MS
      :term: Mississippi
    - :id: MO
      :term: Missouri
    - :id: MT
      :term: Montana
    - :id: NE
      :term: Nebraska
    - :id: NV
      :term: Nevada
    - :id: NH
      :term: New Hampshire
    - :id: NJ
      :term: New Jersey
    - :id: NM
      :term: New Mexico
    - :id: NY
      :term: New York
    - :id: NC
      :term: North Carolina
    - :id: ND
      :term: North Dakota
    - :id: OH
      :term: Ohio
    - :id: OK
      :term: Oklahoma
    - :id: OR
      :term: Oregon
    - :id: PA
      :term: Pennsylvania
    - :id: RI
      :term: Rhode Island
    - :id: SC
      :term: Sourth Carolina
    - :id: SD
      :term: South Dakota
    - :id: TN
      :term: Tennessee
    - :id: TX
      :term: Texas
    - :id: UT
      :term: Utah
    - :id: VT
      :term: Vermont
    - :id: VA
      :term: Virginia
    - :id: WA
      :term: Washington
    - :id: WV
      :term: West Virginia
    - :id: WI
      :term: Wisconsin
    - :id: WY
      :term: Wyoming
