development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/development" %>
test: &test
  adapter: solr
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
test_server:
  adapter: solr
  url: <%= Rails.application.secrets.solr_url %>
production:
  adapter: solr
  url: <%= Rails.application.secrets.solr_url %>