defaults: &defaults
  landing_page_prefix: 'http://collections.durham.ac.uk/'
  datacite_publisher: 'Durham University'
  datacite_rights_holder: 'Durham University'
  datacite_hosting_institution: 'Durham University'
  fetch_doi_prefix: '10.15128'
  fetch_affiliation: 'Durham University, UK'

development:
  <<: *defaults
  doi_prefix: '10.4124'

test:
  <<: *defaults
  doi_prefix: '10.4124'

#testing servers
testing:
  <<: *defaults
  doi_prefix: '10.4124'

production:
  <<: *defaults
  doi_prefix: '10.15128'
