defaults: &defaults
  visibility_notification_users: []
  ark_naan: '12345'
  identifier_template: 'r0.reeddeeddk'
  identifier_statefile: <%= File.expand_path('../minter-state', __FILE__) %>
  visibility_notification_users: []

development:
  <<: *defaults

test:
  <<: *defaults

test_server:
  <<: *defaults
  visibility_notification_users: ['dch1sp']
  identifier_template: <%= "r#{ENV['HYDRA_SERVER_ID'] || '0'}.reeddeeddk" %>

production:
  <<: *defaults
  ark_naan: '32150'
  visibility_notification_users: ['dch1sp']
  identifier_template: <%= "r#{ENV['HYDRA_SERVER_ID'] || '0'}.reeddeeddk" %>
