defaults: &defaults
  visibility_notification_users: []


development:
  <<: *defaults
  visibility_notification_users: []

test:
  <<: *defaults
  visibility_notification_users: ['dch1sp']

production:
  <<: *defaults
  visibility_notification_users: ['dch1sp']
