development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora/rest
  base_path: /test
production:
  url: <%= Rails.application.secrets.fedora_url %>
  base_path: <%= Rails.application.secrets.fedora_base_path %>
