## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  host: <%= Rails.application.secrets.ldap_host %>
  port: 636
  attribute: cn
  base: <%= Rails.application.secrets.ldap_base %>
  ssl: true
  allow_unauthenticated_bind: true
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Environment

development:
  <<: *AUTHORIZATIONS

test:
  <<: *AUTHORIZATIONS

production:
  <<: *AUTHORIZATIONS
