# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8983/solr/development
  select_path: rdm_select
  update_path: rdm_update
test:
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
test_server:
  url: <%= Rails.application.secrets.solr_url %>
# select_path: rdm_select
  update_path: rdm_update
production:
  url: <%= Rails.application.secrets.solr_url %>
# select_path: rdm_select
  update_path: rdm_update